### ISSUE TITLE
Prepare a Motorcycle rental flowchart

### ISSUE THREAD

**Issue by lam3lka** [blockchain-IoT/blockchain-IoT-core#36] opened 2018-03-20 15:22 UTC

**Comment by lam3lka** [comment] 2018-03-20 16:56
As a product owner
to deliver appropriate contracts for vehicle rentals
I need to prepare a motorcycle rental flowchart
which include all events that can occur while motorcycle rental

**Comment by michalmikolajczyk** [comment] 2018-06-25 08:31
duplicate of #17

**Closed by michalmikolajczyk** 2018-06-25 08:31 UTC
