### ISSUE TITLE
Decentralized vehicle rental protocol – assumptiont for smart contracts

### ISSUE THREAD

**Issue by lam3lka** [blockchain-IoT/blockchain-IoT-core#20] opened 2018-02-20 19:31 UTC
As a product owner
to deliver appropriate contracts for vehicle rentals
I need to invent a trustless decentralized protocol
which involves only the motorcycle owner and renter
and involves storing cryptographic proof of the process
and does not involve any relay business
or other central authority

Suggestion
1. Try to depict the algorithm like a flow diagram

**Comment by adamskrodzki** [comment] 2018-03-23 06:53
How this relates to:?
#17

**Comment by michalmikolajczyk** [comment] 2018-06-25 08:29
duplicate of #17

**Closed by michalmikolajczyk** 2018-06-25 08:29 UTC
Labels: good first issue, new feature, top priority
